"""empty message

Revision ID: 16ec3f42f955
Revises: 7983ad0942ad
Create Date: 2020-05-12 22:09:53.491395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ec3f42f955'
down_revision = '7983ad0942ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
