"""empty message

Revision ID: 7983ad0942ad
Revises: e568a0f96fe9
Create Date: 2020-05-12 21:37:14.931842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7983ad0942ad'
down_revision = 'e568a0f96fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.PickleType(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(length=500), nullable=True))
    op.drop_column('venues', 'Genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('Genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
