"""empty message

Revision ID: e687c64c70a9
Revises: e0163c084082
Create Date: 2020-05-13 06:02:16.915901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e687c64c70a9'
down_revision = 'e0163c084082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'name')
    # ### end Alembic commands ###
